### ISSUE TITLE
error in train(args) of retrieve_train.py script

### ISSUE THREAD

**Issue by sahartahmasebi** [VT-NLP/Mocheg#1]
Hi and thank you for promoting Mocheg. I'm facing an error in train(args) function when I'm trying to reproduce the evidence retrieval part. The problem is, in the train set,  there are some DOCUMENT# in text_evidence_qrels_sentence_level.csv file which are not presents in Corpus3_sentence_level.csv. so consequently there is no text for them which causes to "KeyError: '12843-67364-1". where "12843-67364-1" is the DOCUMENT#. please note that I'm using the  complete version of Corpus3_sentence_level.csv which also includes tweets.

**Comment by Barry-Menglong-Yao** [comment]
already updated the dataset files.
