### ISSUE TITLE
The link for downloading checkpoint cannot be accessed. 

### ISSUE THREAD

**Issue by YorickZilin** [VT-NLP/Mocheg#2]
The link for downloading checkpoints cannot be accessed.  Could you please update the link? Thank you very much!

**Comment by adrielkuek** [comment]
Hi, opening this issue once more as the links to the dataset and checkpoints does not seem to be working again. Possible to share the link for both the information?

**Comment by Barry-Menglong-Yao** [comment]
1. Hi, the previous link for the checkpoint is http://nlplab1.cs.vt.edu/~menglong/project/multimodal/fact_checking/MOCHEG/checkpoint/checkpoint.tar.gz. However, it seems the latest google chrome will not trigger the downloading when we click on this URL. If you copy the link and open it in a new google chrome window, you can get the checkpoint file. 

2. To make it easier, I have updated the links for checkpoints and dataset. Please check the [README.md](https://github.com/VT-NLP/Mocheg#readme). Thanks.
