### ISSUE TITLE
Questions about dataset collection, what do you mean by "including the claims that are purely based on text" 

### ISSUE THREAD

**Issue by DanniXu98** [VT-NLP/Mocheg#9]
Hi, Thanks very much for sharing your paper and code! I think it's very inspirng. I have a question about understanding the dataset.

In section 3.1 Data Source in the paper, you mentioned you collected "all necessary information ... including the claims that are purely based on text". What do you mean by "the claims that are purely based on text"? Does it mean you filtered some claims which need images or videos to clear its news content, or you just extract the claims but not the images or videos in the same Snopes or PolitiFact article?

If it means the former one, could you tell me how you filtered the claims?

**Comment by Barry-Menglong-Yao** [comment]
Thanks for your interest! 
For example, in the following PolitiFact article https://www.politifact.com/factchecks/2024/feb/22/donald-trump/fact-check-trump-calls-his-fraud-case-a-form-of-na/, the claim is 'Donald Trump’s fine in the New York fraud case “is a form of Navalny, it is a form of communism or fascism.'

As you can see from this example, the claims in Politifact or Snopes are just text. 
For each claim, journalists in PolitiFact or Snopes will collect information including images and videos to support or refute the claim and write one ruling article to explain their judgement and rationale. Our dataset contains these images in the articles as the "image evidence" as mentioned in our paper.

**Comment by DanniXu98** [comment]
Thanks for your kind explanation!

> Thanks for your interest! For example, in the following PolitiFact article https://www.politifact.com/factchecks/2024/feb/22/donald-trump/fact-check-trump-calls-his-fraud-case-a-form-of-na/, the claim is 'Donald Trump’s fine in the New York fraud case “is a form of Navalny, it is a form of communism or fascism.'
> 
> As you can see from this example, the claims in Politifact or Snopes are just text. For each claim, journalists in PolitiFact or Snopes will collect information including images and videos to support or refute the claim and write one ruling article to explain their judgement and rationale. Our dataset contains these images in the articles as the "image evidence" as mentioned in our paper.
